### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by kedemo** [Keerthikamunagala/github-1#1]
Looks better if the main title is a bit more orange.

styling can be changed like this:

```css
h1 {
  color: #ea9c17;
}
```
